/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NyobaGUI;

/**
 *
 * @author Ardn
 */
class bangun {
public float Lpersegi(float a,float b){
return (a*b);
}
public float Kpersegi(float a, float b){
return (2*(a+b));
}

public float Llingkaran(float a){
    return  (22/7)*a*a;
}
public float Klingkaran(float a){
    return (22/7)*2*a;
}

public float Lsegitiga(float a,float b){
    return (a*b/2);
}
public float Ksegitiga(float a,float b){
    return (a+(2*b));
}

public float Ljajar(float a,float t){
    return (a*t);
}
public float Kjajar(float a,float siMir){
    return (2*(a+siMir));
}
public float Lpersegipanjang(float a,float b){
return (a*b);
}
public float Kpersegipanjang(float a, float b){
return (2*(a+b));
}

public float volBalok(float panjang, float lebar, float tinggi) {
     return (panjang*lebar*tinggi); //To change body of generated methods, choose Tools | Templates.
}

public float lpBalok(float panjang, float lebar,float tinggi) {
     return (2*((panjang*lebar)+(panjang*tinggi)+(lebar*tinggi))); //To change body of generated methods, choose Tools | Templates.
    }

public float volPrismaSegitiga(float alas, float tinggi,float sisi) {
       return (1/2*alas*tinggi); //To change body of generated methods, choose Tools | Templates.
    }

public float lpPrismaSegitiga(float alas, float sisi,float sisiMir, float tinggi) {
        return ((2*1/2*sisi*sisiMir)+((sisi+sisiMir+alas)*tinggi)); //To change body of generated methods, choose Tools | Templates.
    }
public float volTabung(float jari, float tinggi) {
       return (22/7*jari*jari*tinggi); //To change body of generated methods, choose Tools | Templates.
    }

public float lpTabung(float jari,float tinggi) {
        return (2*22/7*jari*(jari+tinggi)); //To change body of generated methods, choose Tools | Templates.
    }

}

public class FrameNyoba extends javax.swing.JFrame {

    /**
     * Creates new form FrameNyoba
     */
    public FrameNyoba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        jButtonPersegi = new javax.swing.JButton();
        jButtonLingkaran = new javax.swing.JButton();
        jButtonHitungdua = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jButtonHitungtiga = new javax.swing.JButton();
        jButtonSegitiga = new javax.swing.JButton();
        jButtonJajar = new javax.swing.JButton();
        jButtonPrisma = new javax.swing.JButton();
        jButtonBalok = new javax.swing.JButton();
        jButtonKerucut = new javax.swing.JButton();
        jButtonBola = new javax.swing.JButton();
        jButtonTabung = new javax.swing.JButton();
        jButtonLimastiga = new javax.swing.JButton();
        jButtonLimasempat = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        jPanelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PersegiPanel = new javax.swing.JPanel();
        jTextPanjang = new javax.swing.JTextField();
        jTextLebar = new javax.swing.JTextField();
        jTextLPersegi = new javax.swing.JTextField();
        jTextKPersegi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LingkaranPanel = new javax.swing.JPanel();
        jTextJari = new javax.swing.JTextField();
        jTextLlingkaran = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextKlingkaran = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SegitigaPanel = new javax.swing.JPanel();
        jTextAlas = new javax.swing.JTextField();
        jTextTinggi = new javax.swing.JTextField();
        jTextSismir = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextKsegitiga = new javax.swing.JTextField();
        jTextLsegitiga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JajarPanel = new javax.swing.JPanel();
        jTextAlasjj = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextTinggijj = new javax.swing.JTextField();
        jTextSismirjj = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextKLuasjj = new javax.swing.JTextField();
        jTextLKlilingjj = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        PrismaPanel = new javax.swing.JPanel();
        jTextAlasjj1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextTinggijj1 = new javax.swing.JTextField();
        jTextSismirjj1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextKLuasjj1 = new javax.swing.JTextField();
        jTextLKlilingjj1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPersegi.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jButtonPersegi.setText("persegi");
        jButtonPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersegiActionPerformed(evt);
            }
        });

        jButtonLingkaran.setText("lingkaran");
        jButtonLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLingkaranActionPerformed(evt);
            }
        });

        jButtonHitungdua.setText("Hitung 2D");
        jButtonHitungdua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHitungduaActionPerformed(evt);
            }
        });

        jButtonHome.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jButtonHome.setText("HOME");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonHitungtiga.setText("Hitung 3D");

        jButtonSegitiga.setText("segitiga siku");
        jButtonSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSegitigaActionPerformed(evt);
            }
        });

        jButtonJajar.setText("jajar genjang");
        jButtonJajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJajarActionPerformed(evt);
            }
        });

        jButtonPrisma.setText("prisma segitiga");
        jButtonPrisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrismaActionPerformed(evt);
            }
        });

        jButtonBalok.setText("balok");
        jButtonBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBalokActionPerformed(evt);
            }
        });

        jButtonKerucut.setText("kerucut");
        jButtonKerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKerucutActionPerformed(evt);
            }
        });

        jButtonBola.setText("bola");
        jButtonBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBolaActionPerformed(evt);
            }
        });

        jButtonTabung.setText("tabung");
        jButtonTabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTabungActionPerformed(evt);
            }
        });

        jButtonLimastiga.setText("limas tiga");
        jButtonLimastiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimastigaActionPerformed(evt);
            }
        });

        jButtonLimasempat.setText("limas empat");
        jButtonLimasempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimasempatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonHitungdua)
                            .addComponent(jButtonHome)
                            .addComponent(jButtonHitungtiga))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonJajar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPrisma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBalok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonKerucut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTabung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLimastiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLimasempat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSegitiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLingkaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPersegi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonPersegi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLingkaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSegitiga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonJajar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonHitungdua)
                .addGap(21, 21, 21)
                .addComponent(jButtonPrisma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBalok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonKerucut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBola)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTabung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimastiga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimasempat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonHitungtiga)
                .addGap(9, 9, 9))
        );

        MainPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Selamat Datang , Pilih menu disamping");

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(103, 103, 103))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        MainPanel.add(jPanelHome, "card4");

        PersegiPanel.setBackground(new java.awt.Color(255, 255, 51));

        jLabel2.setText("Panjang");

        jLabel3.setText("Lebar");

        jLabel4.setText("Luas");

        jLabel5.setText("Keliling");

        javax.swing.GroupLayout PersegiPanelLayout = new javax.swing.GroupLayout(PersegiPanel);
        PersegiPanel.setLayout(PersegiPanelLayout);
        PersegiPanelLayout.setHorizontalGroup(
            PersegiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersegiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersegiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextKPersegi)
                    .addComponent(jTextLPersegi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(jTextPanjang, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextLebar, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PersegiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        PersegiPanelLayout.setVerticalGroup(
            PersegiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersegiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersegiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersegiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(PersegiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PersegiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextKPersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(276, Short.MAX_VALUE))
        );

        MainPanel.add(PersegiPanel, "card2");

        LingkaranPanel.setBackground(new java.awt.Color(0, 153, 153));

        jLabel6.setText("Jari-jari");

        jLabel7.setText("Luas");

        jLabel8.setText("Keliling");

        javax.swing.GroupLayout LingkaranPanelLayout = new javax.swing.GroupLayout(LingkaranPanel);
        LingkaranPanel.setLayout(LingkaranPanelLayout);
        LingkaranPanelLayout.setHorizontalGroup(
            LingkaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LingkaranPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LingkaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextKlingkaran)
                    .addComponent(jTextJari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jTextLlingkaran, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LingkaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(353, Short.MAX_VALUE))
        );
        LingkaranPanelLayout.setVerticalGroup(
            LingkaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LingkaranPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(LingkaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextJari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(44, 44, 44)
                .addGroup(LingkaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLlingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LingkaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextKlingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(278, Short.MAX_VALUE))
        );

        MainPanel.add(LingkaranPanel, "card3");

        SegitigaPanel.setBackground(new java.awt.Color(255, 102, 102));

        jLabel9.setText("Keliling");

        jLabel10.setText("Luas");

        jLabel11.setText("Alas");

        jLabel12.setText("Tinggi");

        jLabel13.setText("Sisi Miring");

        javax.swing.GroupLayout SegitigaPanelLayout = new javax.swing.GroupLayout(SegitigaPanel);
        SegitigaPanel.setLayout(SegitigaPanelLayout);
        SegitigaPanelLayout.setHorizontalGroup(
            SegitigaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SegitigaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SegitigaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SegitigaPanelLayout.createSequentialGroup()
                        .addComponent(jTextAlas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(SegitigaPanelLayout.createSequentialGroup()
                        .addComponent(jTextTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(SegitigaPanelLayout.createSequentialGroup()
                        .addComponent(jTextSismir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(SegitigaPanelLayout.createSequentialGroup()
                        .addGroup(SegitigaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextLsegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextKsegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(SegitigaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        SegitigaPanelLayout.setVerticalGroup(
            SegitigaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SegitigaPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(SegitigaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextAlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SegitigaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SegitigaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSismir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(38, 38, 38)
                .addGroup(SegitigaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SegitigaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(SegitigaPanelLayout.createSequentialGroup()
                        .addComponent(jTextLsegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextKsegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        MainPanel.add(SegitigaPanel, "card5");

        JajarPanel.setBackground(new java.awt.Color(0, 204, 204));

        jLabel14.setText("Alas");

        jLabel15.setText("Tinggi");

        jLabel16.setText("Sisi Miring");

        jLabel17.setText("Luas");

        jLabel18.setText("Keliling");

        javax.swing.GroupLayout JajarPanelLayout = new javax.swing.GroupLayout(JajarPanel);
        JajarPanel.setLayout(JajarPanelLayout);
        JajarPanelLayout.setHorizontalGroup(
            JajarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JajarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JajarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JajarPanelLayout.createSequentialGroup()
                        .addComponent(jTextAlasjj, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(JajarPanelLayout.createSequentialGroup()
                        .addComponent(jTextTinggijj, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(JajarPanelLayout.createSequentialGroup()
                        .addComponent(jTextSismirjj, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addGroup(JajarPanelLayout.createSequentialGroup()
                        .addGroup(JajarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextKLuasjj, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextLKlilingjj, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JajarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        JajarPanelLayout.setVerticalGroup(
            JajarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JajarPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(JajarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextAlasjj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JajarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTinggijj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JajarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSismirjj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(38, 38, 38)
                .addGroup(JajarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JajarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18))
                    .addGroup(JajarPanelLayout.createSequentialGroup()
                        .addComponent(jTextKLuasjj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextLKlilingjj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        MainPanel.add(JajarPanel, "card6");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Alas");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tinggi");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Sisi Miring");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Luas");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Keliling");

        javax.swing.GroupLayout PrismaPanelLayout = new javax.swing.GroupLayout(PrismaPanel);
        PrismaPanel.setLayout(PrismaPanelLayout);
        PrismaPanelLayout.setHorizontalGroup(
            PrismaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrismaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PrismaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrismaPanelLayout.createSequentialGroup()
                        .addComponent(jTextAlasjj1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(PrismaPanelLayout.createSequentialGroup()
                        .addComponent(jTextTinggijj1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20))
                    .addGroup(PrismaPanelLayout.createSequentialGroup()
                        .addComponent(jTextSismirjj1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21))
                    .addGroup(PrismaPanelLayout.createSequentialGroup()
                        .addGroup(PrismaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextKLuasjj1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextLKlilingjj1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PrismaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22))))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        PrismaPanelLayout.setVerticalGroup(
            PrismaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrismaPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PrismaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextAlasjj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrismaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTinggijj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PrismaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSismirjj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(38, 38, 38)
                .addGroup(PrismaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PrismaPanelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23))
                    .addGroup(PrismaPanelLayout.createSequentialGroup()
                        .addComponent(jTextKLuasjj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextLKlilingjj1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        MainPanel.add(PrismaPanel, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersegiActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(PersegiPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        if (jButtonPersegi.isFocusOwner()==true) {
            jTextJari.setText("0");
            jTextAlas.setText("0");
            jTextAlasjj.setText("0");
            jTextSismir.setText("0");
            jTextTinggijj.setText("0");
            jTextTinggi.setText("0");
            jTextSismirjj.setText("0");
            
        }
        
    }//GEN-LAST:event_jButtonPersegiActionPerformed

    private void jButtonLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLingkaranActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(LingkaranPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        if (jButtonLingkaran.isFocusOwner()==true) {
            jTextLebar.setText("0");
            jTextPanjang.setText("0");
            jTextAlas.setText("0");
            jTextAlasjj.setText("0");
            jTextSismir.setText("0");
            jTextTinggijj.setText("0");
            jTextTinggi.setText("0");
            jTextSismirjj.setText("0");
        }
    }//GEN-LAST:event_jButtonLingkaranActionPerformed

    private void jButtonHitungduaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungduaActionPerformed
        // TODO add your handling code here:
        float lebar,panjang,jari,alas,tinggi;
        
        lebar = Float.valueOf(jTextLebar.getText());
        panjang = Float.valueOf(jTextPanjang.getText());
        jari = Float.valueOf(jTextJari.getText());
        alas = Float.valueOf(jTextAlas.getText());
        tinggi = Float.valueOf(jTextTinggi.getText());
        float sismir = Float.valueOf(jTextSismir.getText());
        float alasjj = Float.valueOf(jTextAlasjj.getText());
        float tinggijj = Float.valueOf(jTextTinggijj.getText());
        float sismirjj = Float.valueOf(jTextSismirjj.getText());
        
        
        
        bangun Bangun = new bangun();
        
        jTextLPersegi.setText(String.valueOf(Bangun.Lpersegi(lebar, panjang)));
        jTextKPersegi.setText(String.valueOf(Bangun.Kpersegi(lebar, panjang)));
        jTextLlingkaran.setText(String.valueOf(Bangun.Llingkaran(jari)));
        jTextKlingkaran.setText(String.valueOf(Bangun.Klingkaran(jari)));
        jTextLsegitiga.setText(String.valueOf(Bangun.Lsegitiga(alas, tinggi)));
        jTextKsegitiga.setText(String.valueOf(Bangun.Ksegitiga(alas, sismir)));
        jTextKLuasjj.setText(String.valueOf(Bangun.Ljajar(alasjj, tinggijj)));
        jTextLKlilingjj.setText(String.valueOf(Bangun.Kjajar(alasjj, sismirjj)));
        
        
        
    }//GEN-LAST:event_jButtonHitungduaActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(jPanelHome);
        MainPanel.repaint();
        MainPanel.revalidate();
        
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSegitigaActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(SegitigaPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        if (jButtonLingkaran.isFocusOwner()==true) {
            jTextLebar.setText("0");
            jTextPanjang.setText("0");
            jTextJari.setText("0");
            jTextAlasjj.setText("0");
            jTextTinggijj.setText("0");
            jTextSismirjj.setText("0");
        }
    }//GEN-LAST:event_jButtonSegitigaActionPerformed

    private void jButtonJajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJajarActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(JajarPanel);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        if (jButtonLingkaran.isFocusOwner()==true) {
            jTextLebar.setText("0");
            jTextPanjang.setText("0");
            jTextAlas.setText("0");
            jTextSismir.setText("0");
            jTextJari.setText("0");
            jTextTinggi.setText("0");
        }
            
    }//GEN-LAST:event_jButtonJajarActionPerformed

    private void jButtonPrismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrismaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrismaActionPerformed

    private void jButtonBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBalokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBalokActionPerformed

    private void jButtonKerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKerucutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKerucutActionPerformed

    private void jButtonBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBolaActionPerformed

    private void jButtonTabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTabungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTabungActionPerformed

    private void jButtonLimastigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimastigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimastigaActionPerformed

    private void jButtonLimasempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimasempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimasempatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameNyoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameNyoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameNyoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameNyoba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameNyoba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JajarPanel;
    private javax.swing.JPanel LingkaranPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel PersegiPanel;
    private javax.swing.JPanel PrismaPanel;
    private javax.swing.JPanel SegitigaPanel;
    private javax.swing.JButton jButtonBalok;
    private javax.swing.JButton jButtonBola;
    private javax.swing.JButton jButtonHitungdua;
    private javax.swing.JButton jButtonHitungtiga;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonJajar;
    private javax.swing.JButton jButtonKerucut;
    private javax.swing.JButton jButtonLimasempat;
    private javax.swing.JButton jButtonLimastiga;
    private javax.swing.JButton jButtonLingkaran;
    private javax.swing.JButton jButtonPersegi;
    private javax.swing.JButton jButtonPrisma;
    private javax.swing.JButton jButtonSegitiga;
    private javax.swing.JButton jButtonTabung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JTextField jTextAlas;
    private javax.swing.JTextField jTextAlasjj;
    private javax.swing.JTextField jTextAlasjj1;
    private javax.swing.JTextField jTextJari;
    private javax.swing.JTextField jTextKLuasjj;
    private javax.swing.JTextField jTextKLuasjj1;
    private javax.swing.JTextField jTextKPersegi;
    private javax.swing.JTextField jTextKlingkaran;
    private javax.swing.JTextField jTextKsegitiga;
    private javax.swing.JTextField jTextLKlilingjj;
    private javax.swing.JTextField jTextLKlilingjj1;
    private javax.swing.JTextField jTextLPersegi;
    private javax.swing.JTextField jTextLebar;
    private javax.swing.JTextField jTextLlingkaran;
    private javax.swing.JTextField jTextLsegitiga;
    private javax.swing.JTextField jTextPanjang;
    private javax.swing.JTextField jTextSismir;
    private javax.swing.JTextField jTextSismirjj;
    private javax.swing.JTextField jTextSismirjj1;
    private javax.swing.JTextField jTextTinggi;
    private javax.swing.JTextField jTextTinggijj;
    private javax.swing.JTextField jTextTinggijj1;
    // End of variables declaration//GEN-END:variables
}
