/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ardn
 */
class bangun {
public float Lpersegi(float a,float b){
return (a*b);
}
public float Kpersegi(float a, float b){
return (2*(a+b));
}

public float Lsegitiga(float a,float b){
    return (a*b/2);
}
public float Ksegitiga(float a,float b){
    return (a+(2*b));
}

public float Llingkaran(float a){
    return  (22/7)*a*a;
}
public float Klingkaran(float a){
    return (22/7)*2*a;
}
public float Ljajar(float a,float t){
    return (a*t);
}
public float Kjajar(float a,float siMir){
    return (2*(a+siMir));
}

}

public class jajalgui extends javax.swing.JFrame {

    /**
     * Creates new form jajalgui
     */
    public jajalgui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextPanjang = new javax.swing.JTextField();
        jTextLebar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jhasil = new javax.swing.JLabel();
        jTextHasilLuas = new javax.swing.JTextField();
        jRadioButtonPersegi = new javax.swing.JRadioButton();
        jRadioSegitiga = new javax.swing.JRadioButton();
        jPanjang = new javax.swing.JLabel();
        jLebar = new javax.swing.JLabel();
        jTextTinggi = new javax.swing.JTextField();
        jTinggi = new javax.swing.JLabel();
        jAlas = new javax.swing.JLabel();
        jTextAlas = new javax.swing.JTextField();
        jRadioButtonJajar = new javax.swing.JRadioButton();
        jRadioButtonLingkaran = new javax.swing.JRadioButton();
        jTextSisiMir = new javax.swing.JTextField();
        jJari = new javax.swing.JLabel();
        jHasilLuas = new javax.swing.JLabel();
        jHasilKeliling = new javax.swing.JLabel();
        jTextHasilKel = new javax.swing.JTextField();
        jTextJari = new javax.swing.JTextField();
        jJari1 = new javax.swing.JLabel();
        jPanjang1 = new javax.swing.JLabel();
        jPanjang2 = new javax.swing.JLabel();
        jJari2 = new javax.swing.JLabel();
        jJari3 = new javax.swing.JLabel();
        jTextJari1 = new javax.swing.JTextField();
        jTextJari2 = new javax.swing.JTextField();
        jPanjang3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButtonPersegi1 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jTextHasilLuas1 = new javax.swing.JTextField();
        jTextHasilLuas2 = new javax.swing.JTextField();
        jHasilLuas1 = new javax.swing.JLabel();
        jHasilLuas2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPanjangActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setText("Hitung 2D");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButtonPersegi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonPersegi.setText("Persegi");
        jRadioButtonPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPersegiActionPerformed(evt);
            }
        });

        jRadioSegitiga.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioSegitiga.setText("Segitiga Siku-siku");
        jRadioSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSegitigaActionPerformed(evt);
            }
        });

        jPanjang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanjang.setText("Panjang");

        jLebar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLebar.setText("Lebar");

        jTextTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTinggiActionPerformed(evt);
            }
        });

        jTinggi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTinggi.setText("Tinggi");

        jAlas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jAlas.setText("Alas");

        jTextAlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAlasActionPerformed(evt);
            }
        });

        jRadioButtonJajar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonJajar.setText("Jajar Genjang");
        jRadioButtonJajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJajarActionPerformed(evt);
            }
        });

        jRadioButtonLingkaran.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonLingkaran.setText("Lingkaran");
        jRadioButtonLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLingkaranActionPerformed(evt);
            }
        });

        jTextSisiMir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSisiMirActionPerformed(evt);
            }
        });

        jJari.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jJari.setText("Jari-jari");

        jHasilLuas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jHasilLuas.setText("Luas");

        jHasilKeliling.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jHasilKeliling.setText("Keliling");

        jTextJari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextJariActionPerformed(evt);
            }
        });

        jJari1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jJari1.setText("Sisi Miring");

        jPanjang1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanjang1.setText("Bangun 3D");
        jPanjang1.setToolTipText("");

        jPanjang2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanjang2.setText("Perhitungan Bangun Ruang");

        jJari2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jJari2.setText("Diagonal");

        jJari3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jJari3.setText("Sisi");

        jTextJari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextJari1ActionPerformed(evt);
            }
        });

        jTextJari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextJari2ActionPerformed(evt);
            }
        });

        jPanjang3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanjang3.setText("Bangun 2D");
        jPanjang3.setToolTipText("");

        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButton1.setText("Prisma Segitiga");

        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButton2.setText("Prisma Segiempat/Balok");

        jRadioButton3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButton3.setText("Tabung");

        jRadioButton4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButton4.setText("Kerucut");

        jRadioButton5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButton5.setText("Bola");

        jRadioButton6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButton6.setText("Limas Segiempat");

        jRadioButton7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButton7.setText("Limas Segitiga");

        jRadioButtonPersegi1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButtonPersegi1.setText("Persegi Panjang");
        jRadioButtonPersegi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPersegi1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton2.setText("Hitung 2D");
        jButton2.setActionCommand("Hitung 3D");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jHasilLuas1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jHasilLuas1.setText("Volume");

        jHasilLuas2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jHasilLuas2.setText("Luas Permukaan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanjang)
                    .addComponent(jLebar)
                    .addComponent(jTinggi)
                    .addComponent(jAlas)
                    .addComponent(jJari)
                    .addComponent(jJari1)
                    .addComponent(jJari2)
                    .addComponent(jJari3))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextJari, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextLebar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(jPanjang3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jButton1)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonJajar)
                                    .addComponent(jRadioButtonPersegi1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jHasilKeliling)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextHasilKel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jHasilLuas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextHasilLuas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jHasilLuas1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextHasilLuas1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jHasilLuas2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextHasilLuas2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(44, 44, 44))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextJari2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextJari1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addComponent(jPanjang1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextAlas, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextSisiMir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton6)
                                    .addComponent(jRadioButton7)
                                    .addComponent(jRadioSegitiga)
                                    .addComponent(jRadioButtonPersegi)
                                    .addComponent(jRadioButtonLingkaran)
                                    .addComponent(jButton2))))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(280, Short.MAX_VALUE)
                    .addComponent(jPanjang2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(201, 201, 201)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanjang3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jRadioButtonJajar)
                                .addGap(0, 0, 0)
                                .addComponent(jRadioButtonPersegi1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanjang, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextPanjang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLebar)
                                            .addComponent(jTextLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioSegitiga))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jRadioButtonPersegi)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonLingkaran)
                                .addGap(11, 11, 11)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jJari1)
                                        .addGap(9, 9, 9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextJari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTinggi)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextHasilLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jHasilLuas))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextHasilKel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jHasilKeliling))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextJari2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jJari2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPanjang1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextJari1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jJari3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextAlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAlas)
                    .addComponent(jRadioButton1)
                    .addComponent(jTextHasilLuas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHasilLuas1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSisiMir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jJari)
                    .addComponent(jRadioButton2)
                    .addComponent(jTextHasilLuas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHasilLuas2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addContainerGap(100, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jPanjang2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(567, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPanjangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        float panjang,lebar,alas,tinggi,jari,sisiMir;
        panjang = Float.valueOf(jTextPanjang.getText());
        lebar = Float.valueOf(jTextLebar.getText());
        alas = Float.valueOf(jTextAlas.getText());
        tinggi = Float.valueOf(jTextTinggi.getText());
        jari = Float.valueOf(jTextJari.getText());
        sisiMir = Float.valueOf(jTextSisiMir.getText());
        
        bangun Bangun = new bangun();
        
        if (jRadioButtonPersegi.isSelected()==true) {
            jTextHasilLuas.setText(String.valueOf(Bangun.Lpersegi(panjang, lebar)));
            jTextHasilKel.setText(String.valueOf(Bangun.Kpersegi(panjang, lebar)));
        }
        else if (jRadioSegitiga.isSelected()==true) {
            jTextHasilLuas.setText(String.valueOf(Bangun.Lsegitiga(alas, tinggi)));
            jTextHasilKel.setText(String.valueOf(Bangun.Ksegitiga(alas, sisiMir)));
        }
        else if (jRadioButtonLingkaran.isSelected()==true){
            jTextHasilLuas.setText(String.valueOf(Bangun.Llingkaran(jari)));
            jTextHasilKel.setText(String.valueOf(Bangun.Klingkaran(jari)));
        }
        else if (jRadioButtonJajar.isSelected()==true){
            jTextHasilLuas.setText(String.valueOf(Bangun.Lpersegi(tinggi, alas)));
            jTextHasilKel.setText(String.valueOf(Bangun.Kpersegi(alas, sisiMir)));
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTinggiActionPerformed

    private void jTextAlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAlasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAlasActionPerformed

    private void jRadioButtonPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPersegiActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonPersegi.isSelected()==true) {
            jRadioSegitiga.setSelected(false);
            jRadioButtonJajar.setSelected(false);
            jRadioButtonLingkaran.setSelected(false);
            
            jTextLebar.setEditable(true);
            jTextPanjang.setEditable(true);
            
            jTextAlas.setEditable(false);
            jTextTinggi.setEditable(false);
            jTextSisiMir.setEditable(false);
            jTextJari.setEditable(false);
            
            jTextSisiMir.setText("0");
            jTextAlas.setText("0");
            jTextTinggi.setText("0");
            jTextJari.setText("0");
            jTextPanjang.setText("");
            jTextLebar.setText("");
        }
    }//GEN-LAST:event_jRadioButtonPersegiActionPerformed

    private void jRadioSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSegitigaActionPerformed
        // TODO add your handling code here:
        if (jRadioSegitiga.isSelected()==true) {
            jRadioButtonPersegi.setSelected(false);
            jRadioButtonLingkaran.setSelected(false);
            jRadioButtonJajar.setSelected(false);
            
            jTextAlas.setEditable(true);
            jTextTinggi.setEditable(true);
            jTextSisiMir.setEditable(true);
            
            jTextPanjang.setEditable(false);
            jTextLebar.setEditable(false);
            jTextJari.setEditable(false);
            
            jTextJari.setText("0");
            jTextLebar.setText("0");
            jTextPanjang.setText("0");
            jTextTinggi.setText("");
            jTextAlas.setText("");
            jTextSisiMir.setText("");
            
        }
    }//GEN-LAST:event_jRadioSegitigaActionPerformed

    private void jRadioButtonJajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJajarActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonJajar.isSelected()==true) {
            jRadioSegitiga.setSelected(false);
            jRadioButtonLingkaran.setSelected(false);
            jRadioButtonPersegi.setSelected(false);
            
            jTextTinggi.setEditable(true);
            jTextAlas.setEditable(true);
            jTextSisiMir.setEditable(true);
            
            jTextPanjang.setEditable(false);
            jTextLebar.setEditable(false);
            jTextJari.setEditable(false);
            
            jTextJari.setText("0");
            jTextPanjang.setText("0");
            jTextTinggi.setText("");
            jTextAlas.setText("");
            jTextSisiMir.setText("");
            jTextLebar.setText("0");
        }
        
    }//GEN-LAST:event_jRadioButtonJajarActionPerformed

    private void jRadioButtonLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLingkaranActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonLingkaran.isSelected()==true) {
            jRadioButtonPersegi.setSelected(false);
            jRadioSegitiga.setSelected(false);
            jRadioButtonJajar.setSelected(false);
            
            jTextTinggi.setEditable(false);
            jTextAlas.setEditable(false);
            jTextSisiMir.setEditable(false);
            
            jTextPanjang.setEditable(false);
            jTextLebar.setEditable(false);
            jTextJari.setEditable(true);
             
            
            jTextJari.setText("");
            jTextPanjang.setText("0");
            jTextTinggi.setText("0");
            jTextAlas.setText("0");
            jTextSisiMir.setText("0");
            jTextLebar.setText("0");
            
           
            
        }
    }//GEN-LAST:event_jRadioButtonLingkaranActionPerformed

    private void jTextSisiMirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSisiMirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSisiMirActionPerformed

    private void jTextJariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextJariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextJariActionPerformed

    private void jTextJari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextJari1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextJari1ActionPerformed

    private void jTextJari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextJari2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextJari2ActionPerformed

    private void jRadioButtonPersegi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPersegi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPersegi1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jajalgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jajalgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jajalgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jajalgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jajalgui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAlas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jHasilKeliling;
    private javax.swing.JLabel jHasilLuas;
    private javax.swing.JLabel jHasilLuas1;
    private javax.swing.JLabel jHasilLuas2;
    private javax.swing.JLabel jJari;
    private javax.swing.JLabel jJari1;
    private javax.swing.JLabel jJari2;
    private javax.swing.JLabel jJari3;
    private javax.swing.JLabel jLebar;
    private javax.swing.JLabel jPanjang;
    private javax.swing.JLabel jPanjang1;
    private javax.swing.JLabel jPanjang2;
    private javax.swing.JLabel jPanjang3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButtonJajar;
    private javax.swing.JRadioButton jRadioButtonLingkaran;
    private javax.swing.JRadioButton jRadioButtonPersegi;
    private javax.swing.JRadioButton jRadioButtonPersegi1;
    private javax.swing.JRadioButton jRadioSegitiga;
    private javax.swing.JTextField jTextAlas;
    private javax.swing.JTextField jTextHasilKel;
    private javax.swing.JTextField jTextHasilLuas;
    private javax.swing.JTextField jTextHasilLuas1;
    private javax.swing.JTextField jTextHasilLuas2;
    private javax.swing.JTextField jTextJari;
    private javax.swing.JTextField jTextJari1;
    private javax.swing.JTextField jTextJari2;
    private javax.swing.JTextField jTextLebar;
    private javax.swing.JTextField jTextPanjang;
    private javax.swing.JTextField jTextSisiMir;
    private javax.swing.JTextField jTextTinggi;
    private javax.swing.JLabel jTinggi;
    private javax.swing.JLabel jhasil;
    // End of variables declaration//GEN-END:variables
}
