/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ardn
 */
class bangun {
public float Lpersegi(float a,float b){
return (a*b);
}
public float Kpersegi(float a, float b){
return (2*(a+b));
}

public float Lsegitiga(float a,float b){
    return (a*b/2);
}
public float Ksegitiga(float a,float b){
    return (a+(2*b));
}

public float Llingkaran(float a){
    return  (22/7)*a*a;
}
public float Klingkaran(float a){
    return (22/7)*2*a;
}
}

public class jajalgui extends javax.swing.JFrame {

    /**
     * Creates new form jajalgui
     */
    public jajalgui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextPanjang = new javax.swing.JTextField();
        jTextLebar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jhasil = new javax.swing.JLabel();
        jTextHasilLuas = new javax.swing.JTextField();
        jRadioButtonPersegi = new javax.swing.JRadioButton();
        jRadioSegitiga = new javax.swing.JRadioButton();
        jPanjang = new javax.swing.JLabel();
        jLebar = new javax.swing.JLabel();
        jTextTinggi = new javax.swing.JTextField();
        jTinggi = new javax.swing.JLabel();
        jAlas = new javax.swing.JLabel();
        jTextAlas = new javax.swing.JTextField();
        jRadioButtonJajar = new javax.swing.JRadioButton();
        jRadioButtonLingkaran = new javax.swing.JRadioButton();
        jTextSisiMir = new javax.swing.JTextField();
        jJari = new javax.swing.JLabel();
        jHasilLuas = new javax.swing.JLabel();
        jHasilKeliling = new javax.swing.JLabel();
        jTextHasilKel = new javax.swing.JTextField();
        jTextJari = new javax.swing.JTextField();
        jJari1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPanjangActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButtonPersegi.setText("Persegi");
        jRadioButtonPersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPersegiActionPerformed(evt);
            }
        });

        jRadioSegitiga.setText("Segitiga");
        jRadioSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSegitigaActionPerformed(evt);
            }
        });

        jPanjang.setText("Panjang");

        jLebar.setText("Lebar");

        jTextTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTinggiActionPerformed(evt);
            }
        });

        jTinggi.setText("Tinggi");

        jAlas.setText("Alas");

        jTextAlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAlasActionPerformed(evt);
            }
        });

        jRadioButtonJajar.setText("Jajar Genjang");
        jRadioButtonJajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJajarActionPerformed(evt);
            }
        });

        jRadioButtonLingkaran.setText("Lingkaran");
        jRadioButtonLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLingkaranActionPerformed(evt);
            }
        });

        jTextSisiMir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSisiMirActionPerformed(evt);
            }
        });

        jJari.setText("Jari2");

        jHasilLuas.setText("Luas");

        jHasilKeliling.setText("Luas");

        jTextJari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextJariActionPerformed(evt);
            }
        });

        jJari1.setText("Sisi Miring");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanjang)
                    .addComponent(jLebar)
                    .addComponent(jTinggi)
                    .addComponent(jAlas)
                    .addComponent(jJari)
                    .addComponent(jJari1))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextSisiMir, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jTextJari)
                    .addComponent(jTextAlas)
                    .addComponent(jTextTinggi)
                    .addComponent(jhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPanjang)
                    .addComponent(jTextLebar))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioSegitiga)
                            .addComponent(jRadioButtonPersegi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonLingkaran)
                            .addComponent(jRadioButtonJajar))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jHasilKeliling)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                .addComponent(jTextHasilKel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jHasilLuas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextHasilLuas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton1))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanjang)
                    .addComponent(jRadioButtonPersegi)
                    .addComponent(jRadioButtonLingkaran)
                    .addComponent(jTextHasilLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHasilLuas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioSegitiga)
                        .addComponent(jRadioButtonJajar)
                        .addComponent(jHasilKeliling)
                        .addComponent(jTextHasilKel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLebar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTinggi)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jAlas)
                    .addComponent(jTextAlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jJari)
                    .addComponent(jTextJari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSisiMir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jJari1))
                .addGap(12, 12, 12)
                .addComponent(jhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPanjangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        float panjang,lebar,alas,tinggi,jari,sisiMir;
        panjang = Float.valueOf(jTextPanjang.getText());
        lebar = Float.valueOf(jTextLebar.getText());
        alas = Float.valueOf(jTextAlas.getText());
        tinggi = Float.valueOf(jTextTinggi.getText());
        jari = Float.valueOf(jTextJari.getText());
        sisiMir = Float.valueOf(jTextSisiMir.getText());
        
        bangun Bangun = new bangun();
        
        if (jRadioButtonPersegi.isSelected()==true) {
            jTextHasilLuas.setText(String.valueOf(Bangun.Lpersegi(panjang, lebar)));
            jTextHasilKel.setText(String.valueOf(Bangun.Kpersegi(panjang, lebar)));
        }
        else if (jRadioSegitiga.isSelected()==true) {
            jTextHasilLuas.setText(String.valueOf(Bangun.Lsegitiga(alas, tinggi)));
            jTextHasilKel.setText(String.valueOf(Bangun.Ksegitiga(alas, sisiMir)));
        }
        else if (jRadioButtonLingkaran.isSelected()==true){
            jTextHasilLuas.setText(String.valueOf(Bangun.Llingkaran(jari)));
            jTextHasilKel.setText(String.valueOf(Bangun.Klingkaran(jari)));
        }
        else if (jRadioButtonJajar.isSelected()==true){
            jTextHasilLuas.setText(String.valueOf(Bangun.Lpersegi(tinggi, alas)));
            jTextHasilKel.setText(String.valueOf(Bangun.Kpersegi(alas, sisiMir)));
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTinggiActionPerformed

    private void jTextAlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAlasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAlasActionPerformed

    private void jRadioButtonPersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPersegiActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonPersegi.isSelected()==true) {
            jRadioSegitiga.setSelected(false);
            jRadioButtonJajar.setSelected(false);
            jRadioButtonLingkaran.setSelected(false);
            
            jTextLebar.setEditable(true);
            jTextPanjang.setEditable(true);
            
            jTextAlas.setEditable(false);
            jTextTinggi.setEditable(false);
            jTextSisiMir.setEditable(false);
            jTextJari.setEditable(false);
            
            jTextSisiMir.setText("0");
            jTextAlas.setText("0");
            jTextTinggi.setText("0");
            jTextJari.setText("0");
        }
    }//GEN-LAST:event_jRadioButtonPersegiActionPerformed

    private void jRadioSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSegitigaActionPerformed
        // TODO add your handling code here:
        if (jRadioSegitiga.isSelected()==true) {
            jRadioButtonPersegi.setSelected(false);
            jRadioButtonLingkaran.setSelected(false);
            jRadioButtonJajar.setSelected(false);
            
            jTextAlas.setEditable(true);
            jTextTinggi.setEditable(true);
            jTextSisiMir.setEditable(true);
            
            jTextPanjang.setEditable(false);
            jTextLebar.setEditable(false);
            jTextJari.setEditable(false);
            
            jTextJari.setText("0");
            jTextLebar.setText("0");
            jTextPanjang.setText("0");}
    }//GEN-LAST:event_jRadioSegitigaActionPerformed

    private void jRadioButtonJajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJajarActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonJajar.isSelected()==true) {
            jRadioSegitiga.setSelected(false);
            jRadioButtonLingkaran.setSelected(false);
            jRadioButtonPersegi.setSelected(false);
            
            jTextTinggi.setEditable(true);
            jTextAlas.setEditable(true);
            jTextSisiMir.setEditable(true);
            
            jTextPanjang.setEditable(false);
            jTextLebar.setEditable(false);
            jTextJari.setEditable(false);
            
            jTextJari.setText("0");
            jTextPanjang.setText("0");
            jTextLebar.setText("0");}
    }//GEN-LAST:event_jRadioButtonJajarActionPerformed

    private void jRadioButtonLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLingkaranActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonLingkaran.isSelected()==true) {
            jRadioButtonPersegi.setSelected(false);
            jRadioSegitiga.setSelected(false);
            jRadioButtonJajar.setSelected(false);
            
            jTextJari.setEditable(true);
            
            jTextPanjang.setEditable(false);
            jTextLebar.setEditable(false);
            jTextAlas.setEditable(false);
            jTextTinggi.setEditable(false);
            jTextSisiMir.setEditable(false);
            
            jTextLebar.setText("0");
            jTextPanjang.setText("0");
            jTextAlas.setText("0");
            jTextTinggi.setText("0");
            jTextSisiMir.setText("0");
            
        }
    }//GEN-LAST:event_jRadioButtonLingkaranActionPerformed

    private void jTextSisiMirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSisiMirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSisiMirActionPerformed

    private void jTextJariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextJariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextJariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jajalgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jajalgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jajalgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jajalgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jajalgui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAlas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jHasilKeliling;
    private javax.swing.JLabel jHasilLuas;
    private javax.swing.JLabel jJari;
    private javax.swing.JLabel jJari1;
    private javax.swing.JLabel jLebar;
    private javax.swing.JLabel jPanjang;
    private javax.swing.JRadioButton jRadioButtonJajar;
    private javax.swing.JRadioButton jRadioButtonLingkaran;
    private javax.swing.JRadioButton jRadioButtonPersegi;
    private javax.swing.JRadioButton jRadioSegitiga;
    private javax.swing.JTextField jTextAlas;
    private javax.swing.JTextField jTextHasilKel;
    private javax.swing.JTextField jTextHasilLuas;
    private javax.swing.JTextField jTextJari;
    private javax.swing.JTextField jTextLebar;
    private javax.swing.JTextField jTextPanjang;
    private javax.swing.JTextField jTextSisiMir;
    private javax.swing.JTextField jTextTinggi;
    private javax.swing.JLabel jTinggi;
    private javax.swing.JLabel jhasil;
    // End of variables declaration//GEN-END:variables
}
